
services:
  - type: web
    name: spy-trader
    runtime: node
    buildCommand: bash ./build.sh
    startCommand: node server.js
    env: node
    nodeVersion: 18.19.1
    rootDirectory: ./
    envVars:
      - key: NODE_ENV
        value: production
      - key: NODE_VERSION
        value: 18.19.1
      - key: PYTHON_ENABLED
        value: "0"
      - key: PYTHON_VERSION
        value: "DISABLED"
      - key: PYTHONPATH
        value: "/dev/null"
      - key: PYTHONHOME
        value: "/dev/null"
      - key: POETRY_ENABLED
        value: "0"
      - key: PIP_NO_PYTHON_VERSION_WARNING
        value: "1"
      - key: SKIP_PYTHON
        value: "true"
      - key: USE_PYTHON
        value: "false"
    healthCheckPath: /health
    autoDeploy: true
    # Added resource allocation to ensure adequate resources for Node.js
    plan: starter
    # Adjusted build settings
    buildFilter:
      paths:
        - src/**
        - public/**
        - server.js
        - build.sh
        - vite.config.ts
        - package.json
        - tsconfig*.json
    # Added scaling configuration
    scaling:
      minInstances: 1
      maxInstances: 1
      targetMemoryPercent: 80
    # Added headers for CORS and caching
    headers:
      - path: /*
        name: Cache-Control
        value: max-age=86400
      - path: /assets/*
        name: Cache-Control
        value: max-age=31536000
      - path: /*
        name: X-Frame-Options
        value: DENY
