
services:
  - type: web
    name: spy-trader
    runtime: node
    env: node
    buildCommand: npm install && npm run build
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
    healthCheckPath: /health
    autoDeploy: true
    numInstances: 1
    buildFilter:
      paths:
        - src/**
        - public/**
        - server.js
        - vite.config.ts
    plan: free

