
services:
  - type: web
    name: spy-trader
    runtime: node
    buildCommand: bash ./build.sh
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PYTHON_VERSION
        value: none
      - key: PYTHONPATH
        value: ""
      - key: PYTHONHOME
        value: ""
      - key: NODE_VERSION
        value: 18.19.1
    healthCheckPath: /health
    autoDeploy: true
