// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sklwsxgxsqtwlqjhegms.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNrbHdzeGd4c3F0d2xxamhlZ21zIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA4NDQ5NTEsImV4cCI6MjA1NjQyMDk1MX0.pUI_7m2CPmUyHK9x1ef7b1rWRnSQIeo7KHpYAS9OGHg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);